### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arrygoo** [baijunjie/react-native-input-scroll-view#46]
After I've added `InputScrollView` to my forms, almost 50% of the time, I get the following error:

![screen shot 2019-01-06 at 3 47 44 pm](https://user-images.githubusercontent.com/965429/50741384-8e4d3000-11ca-11e9-8a32-1d1cb465aa0f.png)

Sometimes the error doesn't show at all, but when it does, it happens on every single key press. Happens on both `TextInput multiline` and `TextInput`. Any idea how I can debug this? Removing `InputScrollView` fixes the issue. Looks like it might be related to the `cloneDeep` usage? 

It seems like if I type slowly it doesn't appear, but when I type fast, the error shows up. But sometimes the error shows after each single character too. One more clue is that when this happens, the app becomes really really slow and laggy to respond.

Update:
The problem might be related to navigation as well. If I just have one page, it doesn't happen, but if I navigate from another page to a page that has `InputScrollView` it does happen.

Update2:
I think the issue may be in `_cloneDeepComponents` , as it's recursive. Maybe since it's recursive, it has to load up too many components into memory, and runs out of memory. Maybe if the recursive call is converted to iterative it'll not have the problem anymore?

If you have any ideas on how to debug this further I'd be thankful. 

Also thank you so much for the quick responses on issues! <3

**Comment by baijunjie** [comment]
Hi, can you debug the node on which infinite recursion occurs? I'm not sure if the component has a circular reference?

I saw your description because the text was typed too fast, this may cause your components to be constantly re-rendered, I'm not sure.

Or you can try to modify about ` _cloneDeepComponents ` code, set biggest iteration limit, as long as can meet the actual number of nested components you can. Then see if the error occurs again.

My app doesn't have this problem. Here's the RN version of my app:
```
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4"
```

**Comment by liuxiaofan** [comment]
I have this problem, too.

**Comment by baijunjie** [comment]
HI, please reproduce it using https://snack.expo.io/

**Comment by baijunjie** [comment]
`v1.9.1` solves this problem
