### ISSUE TITLE
Multiline TextInput: Create new line issue

### ISSUE THREAD

**Issue by RobTS** [baijunjie/react-native-input-scroll-view#49]
Hi there,

I can't seem to get the following feature to work: "When the multiline TextInput create new line, the new line will automatically adjust to the top of the keyboard"

On RN 0.58.4 in iOS, with value props and onChangeText set, the multiline text view just becomes bigger, but the scrollview is not following the cursor at all. I have not set any other props so far, but can't see which one's could help here. Is there a working example of this?

**Comment by baijunjie** [comment]
HI, please reproduce it using https://snack.expo.io/

**Comment by Rolandkuku** [comment]
Hello,

I experienced the same issue because my `TextInput` is wrapped inside a custom component.
Did you try to put your `TextInput` as a direct child of `InputScrollView` ?

**Comment by baijunjie** [comment]
TextInput in the child component is theoretically supported.

I need more feedback.

**Comment by Rolandkuku** [comment]
Sorry, I was not being accurate.

This will work:
```
<InputScrollView>
  <View>
     <TextInput />
  </View>
</InputScrollView>
```

But this won’t:
```
const MyComponent = () => (
  <View>
     <TextInput />
  </View>
)

// ...

<InputScrollView>
  <MyComponent />
</InputScrollView>
```

Because when `MyComponent` is passed to [_cloneDeepComponents](https://github.com/baijunjie/react-native-input-scroll-view/blob/master/index.js#L181) it is not yet rendered and React doesn’t know about its props. 

I fixed it by passing down onContentSizeChange, onSelectionChange, and onChange to the `TextInput` inside `MyComponent`.

```
const MyComponent = props => (
  <View>
     <TextInput {...props} />
  </View>
)

// ...

<InputScrollView>
  <MyComponent />
</InputScrollView>
```

**Comment by baijunjie** [comment]
@Rolandkuku Hi, I can't reproduce your problem.
https://snack.expo.io/@baijunjie/issue_49

**Comment by Rolandkuku** [comment]
Hello,

This snack works as expected since you passed all the props from `MyComponent` to the `TextInput`. 

At first, I tried to pass the same props from the example in the readme: `value`, `onChangeText`, and `multiline`. In this scenario, the `TextInput` inside `MyComponent` is missing `onContentSizeChange`, `onSelectionChange`, and `onChange` props for `_addMultilineHandle` to do his job.

This reproduces the issue: https://snack.expo.io/@grollec/issue_49

This is not a bug but I can open a PR to mention it in the README if you want.

**Comment by baijunjie** [comment]
@Rolandkuku Of course do it.
